In [1]:
import torch
torch.__version__

'2.13.0+cu126'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([6, 7])
vector

tensor([6, 7])

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[6,7], [8,9]])
MATRIX

tensor([[6, 7],
        [8, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR =  torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
# Random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.6191, 0.6455, 0.9281, 0.2459],
         [0.3721, 0.2074, 0.4016, 0.4795],
         [0.0616, 0.3763, 0.7222, 0.0344]]),
 torch.float32)

In [15]:
# Random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten, zero_to_ten.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [19]:
ten_zeros= torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # None -> Default (torch.float32)
                               device=None, # Default tensor type
                               requires_grad=False) # if True, operations on this tensor are recorded
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [22]:
some_tensor = torch.rand(3,4)

# Details about some_tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # Default is CPU

tensor([[0.6607, 0.3192, 0.2852, 0.1752],
        [0.3125, 0.1296, 0.9563, 0.7332],
        [0.3108, 0.8891, 0.2661, 0.2518]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [23]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
tensor * 10

tensor([10, 20, 30])

In [25]:
tensor

tensor([1, 2, 3])

In [26]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [27]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [28]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [29]:
tensor

tensor([1, 2, 3])

In [30]:
# Element-wise multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [31]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [32]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# @ can also be used
# for matrix multiplication,
# although it is not recommended.
tensor @ tensor

tensor(14)

In [35]:
%%time
# Matrix mul. by hand
# (avoid using python loops, they are terrible)
value = 0
for i in range(len(tensor)):
    value += tensor[i] + tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(12)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [37]:
# Matrix Multiplication has strict
# dimension rules.
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
# torch.matmul(tensor_A, tensor_B) # This should fail

In [38]:
# View tensor A and B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [39]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [40]:
# If we transpose, the operation works
print(f"Original tensor shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} ")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original tensor shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) 
Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output shape: torch.Size([3, 3])


In [41]:
# torch.mm is short for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [42]:
# Linear layers starts with a random weights matrix,
# so lets make it reproducible:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, # matches inner dimension of input
                         out_features=6) # describes outer valu
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}")
print(f"Output: {output}")
print(f"Output shape: {output.shape}")

# Tweaking it a bit...
linear = torch.nn.Linear(in_features=3,
                         out_features=6)
x = tensor_A.T
output = linear(x)
print(f"\nInput shape: {x.shape}")
print(f"Output: {output}")
print(f"Output shape: {output.shape}")

Input shape: torch.Size([3, 2])
Output: tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
Output shape: torch.Size([3, 6])

Input shape: torch.Size([2, 3])
Output: tensor([[-1.0681,  1.6103, -2.0063, -3.2169,  1.4339,  1.1610],
        [-1.4565,  1.6911, -2.8912, -4.0798,  1.9106,  1.4264]],
       grad_fn=<AddmmBackward0>)
Output shape: torch.Size([2, 6])


In [43]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
print(f"Minimun: {x.min()}")
print(f"Maximun: {x.max()}")
# print(f"Mean   : {x.mean()}") # this will error
print(f"Mean   : {x.type(torch.float32).mean()}") # Mean needs float datatype
print(f"Sum    : {x.sum()}")

Minimun: 0
Maximun: 90
Mean   : 45.0
Sum    : 450


In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [46]:
# Create a tensor
tensor = torch.arange(10,100,10)
print(f"Tensor: {tensor}")

print(f"Max. value index: {tensor.argmax()}")
print(f"Min. value index: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Max. value index: 8
Min. value index: 0


In [47]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [48]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [49]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [50]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [51]:
x_reshaped = x.reshape((1, 7))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
# Changing z changes x, as z is just a different view
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [54]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape : torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [56]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous tensor shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(0)
print(f"New vector: {x_unsqueezed}")
print(f"New vector shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous tensor shape: torch.Size([7])
New vector: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New vector shape: torch.Size([1, 7])


In [57]:
# New vector
x_original = torch.rand(size=(244, 244, 3))

x_permuted = x_original.permute(2, 0, 1) # x_permuted is NOT a new vector, its a view.
print(f"Previous shape: {x_original.shape}")
print(f"New shape     : {x_permuted.shape}")

Previous shape: torch.Size([244, 244, 3])
New shape     : torch.Size([3, 244, 244])


In [58]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
print(f"First dimension: {x[0]}")
print(f"Second dimension: {x[0][0]}")
print(f"Third dimension: {x[0][0][0]}")

First dimension: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second dimension: tensor([1, 2, 3])
Third dimension: 1


In [60]:
x[:, 0]

tensor([[1, 2, 3]])

In [61]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [62]:
x[:, 1, 1]

tensor([5])

In [63]:
x[0, 0, :]

tensor([1, 2, 3])

In [64]:
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor #Numpy usa float64 por defecto

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
# Changing the array doesn't change the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
# tensor += 1 #This one would also change numpy_tensor, because it does not create a new object.
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
# Two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f"random_tensor_A: {random_tensor_A}")
print(f"random_tensor_B: {random_tensor_B}")
print(f"Does A equal B anywhere?")
random_tensor_A == random_tensor_B

random_tensor_A: tensor([[0.0332, 0.4588, 0.0061, 0.1975],
        [0.9903, 0.3102, 0.6397, 0.5341],
        [0.6860, 0.4810, 0.5135, 0.7477]])
random_tensor_B: tensor([[0.8480, 0.7797, 0.8743, 0.5723],
        [0.0469, 0.8472, 0.2916, 0.1722],
        [0.9716, 0.7282, 0.4054, 0.7865]])
Does A equal B anywhere?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [69]:
# Set random seed
RANDOM_SEED = 69420
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"random_tensor_C : {random_tensor_C}")
print(f"random_tensor_D: {random_tensor_D}")
print("Are C and D equal anywhere?")
random_tensor_C == random_tensor_D


random_tensor_C : tensor([[0.9596, 0.8703, 0.3316, 0.6996],
        [0.3577, 0.7450, 0.2780, 0.5310],
        [0.0559, 0.7216, 0.6028, 0.7250]])
random_tensor_D: tensor([[0.9596, 0.8703, 0.3316, 0.6996],
        [0.3577, 0.7450, 0.2780, 0.5310],
        [0.0559, 0.7216, 0.6028, 0.7250]])
Are C and D equal anywhere?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [70]:
!nvidia-smi

Mon Aug 10 12:54:02 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.95                 Driver Version: 581.95         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:01:00.0  On |                  N/A |
| 40%   35C    P5             24W /  170W |    1131MiB /  12288MiB |     13%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [71]:
torch.cuda.is_available()

True

In [72]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [73]:
torch.cuda.device_count()

1

In [74]:
# Create a tensor on CPU
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU
tensor_on_gpu = tensor.to("cuda")
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [75]:
# Numpy doesn't work with GPUs.
# This means you cannot transform a GPU Tensor to numpy:
# tensor_on_gpu.numpy() # This will fail

In [76]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [77]:
# The original tensor is still on cpu
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Notes