# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
torch.manual_seed(67) # This was not mandatory

random_tensor_A = torch.rand((7, 7))
random_tensor_A

tensor([[0.7380, 0.3646, 0.8673, 0.5464, 0.5885, 0.9785, 0.8875],
        [0.9903, 0.3595, 0.3245, 0.8871, 0.9991, 0.5664, 0.5706],
        [0.7217, 0.2157, 0.0415, 0.2903, 0.0052, 0.8127, 0.2556],
        [0.6512, 0.5186, 0.6332, 0.5303, 0.2814, 0.6596, 0.6492],
        [0.0865, 0.3869, 0.6819, 0.2390, 0.8542, 0.7344, 0.8452],
        [0.6987, 0.8547, 0.6188, 0.5371, 0.4756, 0.0563, 0.4369],
        [0.4823, 0.3503, 0.8054, 0.7139, 0.5925, 0.5760, 0.6001]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor_B = torch.rand((1, 7))
# Perform matrix multiplication
A_dot_B = torch.matmul(random_tensor_A, random_tensor_B.T)
print(random_tensor_B)
print(A_dot_B)

tensor([[0.7417, 0.0029, 0.3852, 0.3063, 0.7652, 0.3698, 0.8447]])
tensor([[2.6116],
        [2.5883],
        [1.1612],
        [1.8985],
        [2.0403],
        [1.6774],
        [2.0609]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_A = torch.rand((7, 7))
random_tensor_B = torch.rand((1, 7))

# Matrix multiply tensors
result = torch.mm(random_tensor_A, random_tensor_B.T)

# Output
print("random_tensor_A:")
print(random_tensor_A)

print("\nrandom_tensor_B:")
print(random_tensor_B)

print("\nMat. Mul. result:")
print(result)

random_tensor_A:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

random_tensor_B:
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

Mat. Mul. result:
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
gpu_random_A = torch.rand((2, 3)).to(device)
gpu_random_B = torch.rand((2, 3)).to(device)

print(gpu_random_A)
print(gpu_random_B)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
gpu_A_dot_B = torch.mm(gpu_random_A, gpu_random_B.T)
gpu_A_dot_B, gpu_A_dot_B.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print(gpu_A_dot_B.max())
# Find min
print(gpu_A_dot_B.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(gpu_A_dot_B.argmax())
# Find arg min
print(gpu_A_dot_B.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand((1,1,1,10))

# Remove single dimensions
random_tensor_squeezed = torch.squeeze(random_tensor)
# Print out tensors and their shapes
random_tensor, random_tensor.shape, random_tensor_squeezed, random_tensor_squeezed.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))